## 00.pytorch

# hello Rakibul



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensor

In [ ]:
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
vector = torch.tensor([7,7])
vector.shape
matrix = torch.tensor(
    [
    [1,2,3],
    [3,4,5]
    ])
matrix.shape

torch.Size([2, 3])

In [ ]:
Tensor = torch.tensor(
    [
        [
            [1,2,3],
            [2,3,4],
            [4,5,6]
        ],
        [
            [1,2,3],
            [2,3,4],
            [4,5,6]
        ]
    ]
)
Tensor.shape

torch.Size([2, 3, 3])

In [ ]:
Tensor = torch.rand(2,783,4)
Tensor

tensor([[[0.0624, 0.9278, 0.9199, 0.3177],
         [0.4476, 0.9571, 0.4103, 0.0925],
         [0.9378, 0.2572, 0.7056, 0.5587],
         ...,
         [0.7559, 0.7593, 0.2217, 0.8537],
         [0.0112, 0.6629, 0.7584, 0.4439],
         [0.8697, 0.5752, 0.0885, 0.7336]],

        [[0.4803, 0.9970, 0.6222, 0.1772],
         [0.5992, 0.0719, 0.0254, 0.2123],
         [0.3611, 0.8968, 0.4111, 0.0021],
         ...,
         [0.9802, 0.2425, 0.1395, 0.0627],
         [0.4468, 0.9515, 0.3749, 0.3188],
         [0.1735, 0.3782, 0.9313, 0.9462]]])

In [ ]:
tensor = torch.rand(2,16,16)
tensor

tensor([[[4.6206e-01, 8.0887e-01, 3.4978e-01, 2.4426e-01, 1.5863e-01,
          7.5548e-01, 5.8041e-01, 9.6334e-01, 7.3653e-01, 4.7151e-01,
          8.5411e-01, 5.2433e-01, 7.2714e-02, 7.8439e-01, 1.7960e-01,
          1.8847e-01],
         [9.5141e-01, 5.3090e-01, 8.8266e-02, 2.3655e-01, 2.0782e-02,
          6.3539e-01, 2.3656e-01, 3.7293e-01, 1.7643e-01, 3.4523e-01,
          6.5831e-01, 8.8921e-01, 1.8440e-01, 6.1833e-01, 4.6655e-01,
          5.8889e-01],
         [9.7479e-01, 4.1417e-01, 6.6807e-01, 9.1309e-01, 7.3606e-02,
          6.1225e-01, 4.9753e-01, 2.8471e-01, 9.4607e-01, 5.4736e-01,
          4.8868e-01, 9.1087e-01, 3.0348e-01, 6.2650e-01, 3.7552e-01,
          7.1612e-01],
         [3.5620e-02, 2.4741e-01, 4.1832e-01, 5.9314e-01, 7.8747e-01,
          4.1221e-01, 5.1800e-01, 1.6785e-01, 5.8249e-01, 9.6668e-01,
          8.9710e-01, 9.5599e-01, 7.9961e-02, 4.9622e-01, 1.3043e-01,
          2.9786e-01],
         [6.1871e-01, 9.0102e-01, 8.9928e-01, 5.5891e-01, 7.7588e-01

In [ ]:
tensor = torch.zeros(size=(10,10,10))
tensor

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [ ]:
tensor = torch.arange(1,11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tensor = torch.arange(1,11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tensor = torch.zeros_like(tensor)
tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
tensor_32 = torch.tensor([1.0,2.0,9.0],
                         dtype=None,
                         device=None,
                         requires_grad=False)
tensor_32.dtype,tensor_32.device,tensor_32.requires_grad

(torch.float32, device(type='cpu'), False)

In [ ]:
tensor_16 = tensor_32.type(torch.float16)
tensor_16,tensor_16.dtype

(tensor([1., 2., 9.], dtype=torch.float16), torch.float16)

In [ ]:
tensor_16 * tensor_32

tensor([ 1.,  4., 81.])

In [ ]:
matA = torch.rand(3,2)
matB = torch.rand(2,3)
matA.matmul(matB),(matA @ matB).shape


(tensor([[0.3499, 0.1004, 0.3569],
         [0.8566, 0.4635, 1.1189],
         [0.6678, 0.4614, 0.9849]]),
 torch.Size([3, 3]))

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error) we need 3x2 and 2x3 or
tensor_A,tensor_B,tensor_A.shape,tensor_B.shape


(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]),
 torch.Size([3, 2]))

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error) we need 3x2 and 2x3 or
tensor_A,tensor_B,tensor_A.shape,tensor_B.shape
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# Aggregate functions of tensors
x = torch.arange(1,100,10,dtype=torch.int32)
x.dtype

torch.int32

In [ ]:
torch.mean(x.type(torch.float32))


tensor(46.)

In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
x.dtype

torch.int32

In [ ]:

import torch
x = torch.arange(1,17,dtype=torch.float32)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16.])

In [ ]:
x_shaped = x.reshape(2,8) # reshape will be support base on x.shape or x.size() -> here 16 -> 1x16,2x8,4x4,vice versa
x_shaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16.]])

In [ ]:
#view
z = x.view(4,4)
z[0][1] =100.
z,x

(tensor([[  1., 100.,   3.,   4.],
         [  5.,   6.,   7.,   8.],
         [  9.,  10.,  11.,  12.],
         [ 13.,  14.,  15.,  16.]]),
 tensor([  1., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.]))

In [ ]:
tensor_stack = torch.stack([x,x,x,x,x],dim=1)#dim = 0 -> vertical stack , 1 -> horizontal stack
tensor_stack

tensor([[  1.,   1.,   1.,   1.,   1.],
        [100., 100., 100., 100., 100.],
        [  3.,   3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.,   9.],
        [ 10.,  10.,  10.,  10.,  10.],
        [ 11.,  11.,  11.,  11.,  11.],
        [ 12.,  12.,  12.,  12.,  12.],
        [ 13.,  13.,  13.,  13.,  13.],
        [ 14.,  14.,  14.,  14.,  14.],
        [ 15.,  15.,  15.,  15.,  15.],
        [ 16.,  16.,  16.,  16.,  16.]])

In [ ]:
x_shaped

tensor([[  1., 100.,   3.,   4.,   5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.]])

In [ ]:
x_shaped.squeeze()

tensor([[  1., 100.,   3.,   4.,   5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.]])

In [ ]:
x

tensor([  1., 100.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.])

In [ ]:
x.shape

torch.Size([16])

In [ ]:
# prompt: give me eample of torch squeeze easy example

# Create a tensor with a dimension of size 1
x_unsqeezed = torch.randn(1,10, 1)
print(f"Original tensor: {x_unsqeezed}\n")
print(f"Original shape: {x_unsqeezed.shape}\n")
# Remove the dimension of size 1
x_squeezed = x_unsqeezed.squeeze()
print(f"Squeezed tensor: {x_squeezed}\n")
print(f"Squeezed shape: {x_squeezed.shape}")

Original tensor: tensor([[[ 0.4665],
         [ 1.7447],
         [-0.9060],
         [ 0.0469],
         [-0.3940],
         [ 0.5177],
         [-1.6747],
         [ 1.7012],
         [ 0.9453],
         [-1.0716]]])

Original shape: torch.Size([1, 10, 1])

Squeezed tensor: tensor([ 0.4665,  1.7447, -0.9060,  0.0469, -0.3940,  0.5177, -1.6747,  1.7012,
         0.9453, -1.0716])

Squeezed shape: torch.Size([10])


In [ ]:
# prompt: give me   easy example of unsqueeze

# Add an extra dimension at a specific position
x_unsqueeze = x_squeezed.unsqueeze(dim=0) # Add a dimension of size 1 at the beginning
print(f"Unsqueeze at dim 0: {x_unsqueeze}\n")
print(f"Shape after unsqueeze at dim 0: {x_unsqueeze.shape}")

x_unsqueeze = x_squeezed.unsqueeze(dim=1) # Add a dimension of size 1 at index 1
print(f"Unsqueeze at dim 1: {x_unsqueeze}\n")
print(f"Shape after unsqueeze at dim 1: {x_unsqueeze.shape}")

# Add an extra dimension at the end (equivalent to unsqueeze(dim=-1))
x_unsqueeze = x_squeezed.unsqueeze(dim=-1)
print(f"Unsqueeze at dim -1 (end): {x_unsqueeze}\n")
print(f"Shape after unsqueeze at dim -1: {x_unsqueeze.shape}")


Unsqueeze at dim 0: tensor([[ 0.4665,  1.7447, -0.9060,  0.0469, -0.3940,  0.5177, -1.6747,  1.7012,
          0.9453, -1.0716]])

Shape after unsqueeze at dim 0: torch.Size([1, 10])
Unsqueeze at dim 1: tensor([[ 0.4665],
        [ 1.7447],
        [-0.9060],
        [ 0.0469],
        [-0.3940],
        [ 0.5177],
        [-1.6747],
        [ 1.7012],
        [ 0.9453],
        [-1.0716]])

Shape after unsqueeze at dim 1: torch.Size([10, 1])
Unsqueeze at dim -1 (end): tensor([[ 0.4665],
        [ 1.7447],
        [-0.9060],
        [ 0.0469],
        [-0.3940],
        [ 0.5177],
        [-1.6747],
        [ 1.7012],
        [ 0.9453],
        [-1.0716]])

Shape after unsqueeze at dim -1: torch.Size([10, 1])


In [26]:
!git config --global user.email "rakibulislam28169@gmail.com"
!git config --global user.name "Rakib-28169-islam"


In [27]:
!git clone https://github.com/Rakib-28169-islam/Deep-Learning-Practise.git

Cloning into 'Deep-Learning-Practise'...


In [28]:
!cp 00_pytourch_fundamentals.ipynb /content/Deep-Learning-Practise/


cp: cannot stat '00_pytourch_fundamentals.ipynb': No such file or directory


In [30]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/


In [31]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	Deep-Learning-Practise/
	sample_data/

nothing added to commit but untracked files present (use "git add" to track)


In [32]:
!git add .

error: 'Deep-Learning-Practise/' does not have a commit checked out
fatal: adding files failed


In [33]:
!cp 00_pytorch_fundamentals.ipynb /content/Deep-Learning-Practise/


cp: cannot stat '00_pytorch_fundamentals.ipynb': No such file or directory


In [2]:
!ls /content

drive  sample_data


In [3]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [8]:
!cp "/content/drive/MyDrive/Colab Notebooks/00_pytourch_fundamentals.ipynb" /content/Deep-Learning-Practise/


cp: cannot create regular file '/content/Deep-Learning-Practise/': Not a directory


In [9]:
!git clone https://github.com/your-username/Deep-Learning-Practise.git


Cloning into 'Deep-Learning-Practise'...
fatal: could not read Username for 'https://github.com': No such device or address
